### ISSUE TITLE
Abestop AT252

### ISSUE THREAD

**Issue by mikerocklewitz** [fuho/owon_hds200#1]
I just got an Abestop branded AT252.  50mhz no sig gen.  Looks pretty identical to the hds242 or similar, board is branded hds200, and manufacturer informed me its all the same factory.

Firmware is  V8.4.0.  Not sure if anyone knows anything about this thing but if i get any files that arent shared elsewhere, i will share them here.

it uses same pc software and driver as the owon's....

**Comment by fuho** [comment]
Great! I haven't heard about this version yet. If you feel like taking photos of the outside/inside and creating a PR I'll gladly merge it in.

**Comment by mikerocklewitz** [comment]
I forked the repo but im not exactly sure how to go about doing a proper PR to add it.

Ill add it here though.
![20241025_071423](https://github.com/user-attachments/assets/15238a99-f32f-41b9-b5e0-faa0915a51b9)

![20241025_071437-EDIT](https://github.com/user-attachments/assets/a5c6399d-9fb1-4cef-8701-e2e3f6c3ab74)
![20241025_071557-EDIT](https://github.com/user-attachments/assets/c434e970-7108-4d0c-b6b7-113a7bef9356)

**Comment by fuho** [comment]
Thanks! Added the photos here: https://github.com/fuho/owon_hds200/commit/4b4f4c5079eb21aade82728a94f3a4b057832b0b

**Comment by mikerocklewitz** [comment]
Last night I got sent firmware 8.8.1 (or 8.8.2, I forget but either way its from 8.4 tob 8.8🤣) for this scope.  They asked for serial number and current version info to provide me the file so I wouldnt use it if your versions dont match...

So if anybody wants the files use at your own risk
https://drive.google.com/drive/folders/1oJjCc2klcHciNA-CV_7auPeGbrDx5gSs
